### ISSUE TITLE
Analyzing SPV shaders on a machine without AMD driver installed results in errors

### ISSUE THREAD

**Issue by kayru** [GPUOpen-Tools/RGA#13]
Steps to reproduce:

- Use trivial shader `test.comp`:
```
#version 450
void main()
{
}
```
- Compile to spv: `glslc test.comp`
- Analyze result using `-s vulkan-spv a.spv --asic Fiji --isa .` to get error `Building for Fiji... failed.`

**Comment by AmitBM** [comment]
Hi kayru,
Thanks for reporting this issue. We will look into that.

**Comment by AmitBM** [comment]
Hi kayru, 
You need to specify the stage for the input shader, for example:
-s vulkan-spv **--vert** a.spv -c Fiji --isa c:\temp\output\isa.txt
Please let us know if that solved your issue.

**Comment by kayru** [comment]
Yup, that works! Perhaps a more specific error could be reported for this?
