### ISSUE TITLE
Cannot build with VS2017

### ISSUE THREAD

**Issue by robinchrist** [GPUOpen-Tools/RGA#16]
Hello,

I am using the newest VS2017 Enterprise Release, but Building RGA in Release Mode does not work.
I get the following errors:
`LNK1104	cannot open file 'libboost_filesystem-vc140-mt-1_59.lib'	RadeonGPUAnalyzerCLI	D:\RGA-master\Build\CMake\VS2017\RadeonGPUAnalyzerCLI	D:\RGA-master\Build\CMake\VS2017\RadeonGPUAnalyzerCLI\LINK	1	Build	`

`LNK4075	ignoring '/EDITANDCONTINUE' due to '/OPT:ICF' specification	RadeonGPUAnalyzerCLI	D:\RGA-master\Build\CMake\VS2017\RadeonGPUAnalyzerCLI	D:\RGA-master\Build\CMake\VS2017\RadeonGPUAnalyzerCLI\tinyxml2-d.lib(tinyxml2.obj)	1	Build	`

`LNK2038	mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MD_DynamicRelease' in kcCLICommander.obj	RadeonGPUAnalyzerCLI	D:\RGA-master\Build\CMake\VS2017\RadeonGPUAnalyzerCLI	D:\RGA-master\Build\CMake\VS2017\RadeonGPUAnalyzerCLI\libboost_system-vc140-mt-gd-1_59.lib(error_code.obj)	1	Build	
`
`LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in kcCLICommander.obj	RadeonGPUAnalyzerCLI	D:\RGA-master\Build\CMake\VS2017\RadeonGPUAnalyzerCLI	D:\RGA-master\Build\CMake\VS2017\RadeonGPUAnalyzerCLI\libboost_system-vc140-mt-gd-1_59.lib(error_code.obj)	1	Build	`

Building in Debug mode seems to work.

**Comment by AmitBM** [comment]
Hi robinchrist, 
As mentioned in the README.md file, you should pass the "--vs 2017" argument to the prebuild.bat script in order to generate a Visual Studio 2017 solution file.

**Comment by robinchrist** [comment]
Hi @AmitBM,
Without `--vs 2017` it is not possible to build anything, because the prebuild script cannot finish (`Running cmake to generate a VisualStudio solution...
CMake Error at CMakeLists.txt:2 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:`).
Therefore it is necessary to specify `--vs 2017` in any case.
Note: The DEBUG build **works fine**! Only the release build with `--vs2017 --build release` **does fail**.

**Comment by AmitBM** [comment]
Hi robinchrist, 
Can you please remove the Build\CMake sub-folder and then rerun prebuild.bat with --vs 2017 and --build release?
We suspect that the issue happens because the Debug and Release build files get written into the same directory. We will update the script so that it writes to a separate sub-directory (Debug, Release) depending on the configuration.

**Comment by AmitBM** [comment]
Hi robinchrist,

Did the last comment solve your issue?
