### ISSUE TITLE
Building for Vega?

### ISSUE THREAD

**Issue by Groovounet** [GPUOpen-Tools/RGA#17]
Hi,
Is there a way to build for Vega? 
Looking at the code, it doesn't seem it's supported yet. Am I correct?

**Comment by AmitBM** [comment]
Hi Groovounet,

RGA supports building for Vega in most of its modes. Some modes depend on the installed driver.
What API are you targeting?

**Comment by Groovounet** [comment]
OpenGL

**Comment by AmitBM** [comment]
OpenGL does not support Vega as a target GPU. This is a known issue. We will increase the priority for this feature.

**Comment by Groovounet** [comment]
Thanks! :)

**Comment by Groovounet** [comment]
I also noticed that GL_AMD_shader_atomic_counter_ops is not supported

**Comment by AmitBM** [comment]
Hi Groovounet, baldurk, 

You should be able to build OpenGL shaders for Vega targets with RGA 2.1 (released today). Please make sure to use the latest AMD driver.
