### ISSUE TITLE
Include paths containing spaces are not passed correctly to clang

### ISSUE THREAD

**Issue by georgevanvenrooij** [GPUOpen-Tools/RGA#19]
When running RGA on Windows, I get the following error:

```
rga -s cl --list-kernels apply_local_velocity.cl -I "..\build\Visual Studio 14 Win64\ecs4"

Error (reported by the ROCm OpenCL Compiler):
clang.exe: error: no such file or directory: 'Studio'
clang.exe: error: no such file or directory: '14'
clang.exe: error: no such file or directory: 'Win64\ecs4'
```

**Comment by AmitBM** [comment]
Hi georgevanvenrooij,

Thanks for reporting this issue. 

It is a known bug, which will be fixed in the upcoming RGA release (hopefully in March).

**Comment by AmitBM** [comment]
Hi georgevanvenrooij,

RGA 2.0, which was released today, should contain a fix for this issue.
We hope that you enjoy the new graphical user interface.
