### ISSUE TITLE
Crash when compiling a simple kernel with `--line-numbers`

### ISSUE THREAD

**Issue by fo-fo** [GPUOpen-Tools/RGA#20]
This simple OpenCL kernel crashes clang in RGA when compiled with `--line-numbers`:

```opencl
__kernel void apply_gamma(
    __global float3 *result,
    const __global float3 *input)
{
    const int id = get_global_id(0);
    result[id] = powr(input[id], 0.454545f);
}
```
Compiled with:
`./rga -s rocm-cl --isa isa.txt --line-numbers apply_gamma.cl`

OS: *Ubuntu 16.04.3 LTS*
Version: *rga-1.4.172* (from releases)

**Comment by AmitBM** [comment]
Hi fo-fo,

Thanks for reporting this issue.
A fix will be included in the upcoming RGA release.

**Comment by fo-fo** [comment]
Any time frame for the next release?

**Comment by AmitBM** [comment]
Hi fo-fo,

The current target for the next release is late March.

**Comment by AmitBM** [comment]
Hi fo-fo,

RGA 2.0 was released today, and should contain a fix for this issue.

We hope that you enjoy the new graphical user interface.

**Comment by fo-fo** [comment]
Thanks. It seems to be fixed.
