### ISSUE TITLE
UpdateCommon.py leaves scriptRoot and causes permission issues

### ISSUE THREAD

**Issue by grische** [GPUOpen-Tools/RGA#21]
Currently the python script ``UpdateCommon.py`` leaves its root folder and tries to create folders in a parent directory. This is rather bad as the executing user might not have access to the parent folder and hence runs into security restrictions.

See:
https://github.com/GPUOpen-Tools/RGA/blob/3328dddb9ff23d32b537c0f0d4152b8850197c27/UpdateCommon.py#L16-L48

For instance, executing ``./prebuild.sh --build release`` caues these errors:

```
Directory /mnt/ext_projects/Common/Src/ShaderUtils does not exist, using 'git clone' to get latest from https://github.com/GPUOpen-Tools/common-src-ShaderUtils.git
fatal: could not create leading directories of '/mnt/ext_projects/Common/Src/ShaderUtils': Permission denied
git clone failed with 128

Directory /mnt/ext_projects/Common/Src/CElf does not exist, using 'git clone' to get latest from https://github.com/GPUOpen-Tools/common-src-CElf.git
fatal: could not create leading directories of '/mnt/ext_projects/Common/Src/CElf': Permission denied
git clone failed with 128
```

**Comment by AmitBM** [comment]
Hi grische,

This behavior is not specific to RGA, this is how other GPUOpen-Tools products behave. This allows developers who work on multiple repositories to have a single, shared, copy of the Common folder (which can get quite large).

Is there anything preventing you from creating an additional sub-directory to bypass the permissions issue?

**Comment by grische** [comment]
@AmitBM yes, it is possible to use some workaround, like creating a parent directory, add it to git and add the other modules as submodules (that way, git can automatised update the "basefolder" like in other projects).

A more clean workaround would be to add a parameter which represents the ``../`` and which can be overridden to be anywhere, but it requires build/code adjustments of course.

When I opened the issue here, I was expecting a similar approach to GPUOpen-Tools/CodeXL@d5fa44842a95d6fa576d6ea7811c5d721039614f which uses a more common approach imho. But as far as I understand this is not in your interest at the moment.

**Comment by AmitBM** [comment]
Hi grische,

That is correct. In spite of the benefits in making the Common folder's location configurable, we would prefer to avoid this approach for now.

Thanks for reporting and using RGA.
