### ISSUE TITLE
Shader model above 5.0 not supported in HLSL

### ISSUE THREAD

**Issue by onatto** [GPUOpen-Tools/RGA#22]
Error: unsupported Shader Model detected: ps_5_1. RGA supports Shader Model 5.0 and below.

**Comment by AmitBM** [comment]
Hi onatto,

As the error mentions, RGA does not support Shader Model 5.1 and above currently. 
Support for these shader models is in our future feature list.

**Comment by michal-z** [comment]
Hi, do you have ETA for this? Thanks!

**Comment by AmitBM** [comment]
Hi michal-z,

We currently do not have a target date for this feature.

**Comment by giordi91** [comment]
I would like to subscribe to this as well. Would love to have higher Shader Model than 5.0 since I am targeting those.

**Comment by AmitBM** [comment]
Hi onatto, michal-z, giordi91,
RGA 2.3, which was released today, adds support for shader model 5.1 and above in the command line tool's DX12 mode (-s dx12). Please check [this article](https://gpuopen.com/radeon-gpu-analyzer-2-3-direct3d-12-graphics/) for details.

**Comment by giordi91** [comment]
This is great! Thank you! Been looking forward to this!
