### ISSUE TITLE
Support for non-Vega GPU's with `-s rocm-cl`

### ISSUE THREAD

**Issue by zawawawa** [GPUOpen-Tools/RGA#25]
```
C:\> rga.exe -s rocm-cl test.cl -b test.bin

Building for gfx900... succeeded.
Building for gfx902... succeeded.

C:\>
```
Please add support for gfx803 and other GPU's.

**Comment by AmitBM** [comment]
Hi zawawawa,

We will do our best to add support for pre-Vega GPUs in the next release.

**Comment by AmitBM** [comment]
Hi zawawawa,

RGA 2.0.1, which was released today, has support for select pre-Vega targets. Please note that, in addition, you can now extend the list of supported targets by manually editing the addtional-targets text file. Please see the “Alternative ROCm OpenCL compiler” section in the help manual for rocm-cl mode (–s rocm-cl –h) for more information.
