### ISSUE TITLE
Failed to disassemble binary output and produce textual ISA code

### ISSUE THREAD

**Issue by robinchrist** [GPUOpen-Tools/RGA#27]
Hi,

RGA does not work for me.

`/rga -s cl -c Tonga --cfg /home/robin/output/cfg.dot --livereg /home/robin/output/regs.txt --analysis /home/robin/analysis.vsc -D NUMINTEGRATIONPOINTS=8 /home/robin/kernel.txt
`
Output:
```
Target GPU detected:

Tonga (Graphics IP v8)
        AMD FirePro S7100X
        AMD FirePro S7150
        AMD FirePro W7100
        AMD MxGPU
        AMD RADEON R9 M390X
        AMD RADEON R9 M395X
        AMD Radeon (TM) R9 380 Series
        AMD Radeon (TM) R9 M390X
        AMD Radeon R9 200 Series

Building for Tonga... succeeded.
```
**Error: failed to disassemble binary output and produce textual ISA code for Tonga (kernel: formMatrices).**
[kernel.txt](https://github.com/GPUOpen-Tools/RGA/files/2119540/kernel.txt)

System:
TR1950X, R9 390X
Kubuntu 17.10
Kernel 4.13.0-45-generic

UPDATE:
It was a driver problem with AMDGPU-PRO 18.10, Works with 18.20 (however, nothing was mentioned in the release notes)

**Comment by AmitBM** [comment]
Hi robinchrist,

Thanks for sharing this. We will make sure to update the release notes with a new minimum AMDGPU-PRO driver version.
