### ISSUE TITLE
Documentation for "Ra" in live register analysis is wrong

### ISSUE THREAD

**Issue by tgjones** [GPUOpen-Tools/RGA#30]
https://github.com/GPUOpen-Tools/RGA/blob/988567759fe7776210349b5791a3e0804308c8f3/Core/ShaderAnalysis/src/shae.py#L719

Instead of "Number of allocated registers", this should say "Number of live registers".

My source: Matthäus G. Chajdas said so :)

https://twitter.com/NIV_Anteru/status/1033609068533956609

**Comment by AmitBM** [comment]
Hi tgjones,

This will be fixed in the next update of the code. 
Thanks for reporting this issue.

**Comment by AmitBM** [comment]
Hi tgjones,

This should be fixed with today's changes (c7d81b610fa293dfa7bc38117314f7401fefc578).

**Comment by AmitBM** [comment]
Hi tgjones, 

This should be fixed with today's changes (c7d81b610fa293dfa7bc38117314f7401fefc578).

**Comment by tgjones** [comment]
The fix looks good to me.
