### ISSUE TITLE
Add CLI option (or change the default) to generate per basic-block CFG

### ISSUE THREAD

**Issue by tgjones** [GPUOpen-Tools/RGA#31]
At the moment, `rga.exe --cfg` will give you a per instruction CFG, because of this line:

https://github.com/GPUOpen-Tools/RGA/blob/988567759fe7776210349b5791a3e0804308c8f3/RadeonGPUAnalyzerBackend/src/beStaticIsaAnalyzer.cpp#L114

Matthäus suggested the default could be per basic-block (https://twitter.com/NIV_Anteru/status/1033794778230677504). As far as I can tell this could be done by simply changing `dump-pi-cfg` to `dump-bb-cfg`, but I don't know if backwards compatibility is a concern, in which case a new CLI argument might be required.

**Comment by AmitBM** [comment]
Hi tgjones,

Today's changes (c7d81b610fa293dfa7bc38117314f7401fefc578) should enable per basic-block CFG generation:
--cfg    -> generate a per basic-block CFG (default).
--cfg-i  -> generate a per instruction CFG.

Please let us know if this has solved the issue.

**Comment by tgjones** [comment]
This is great, thank you! My build script for Shader Playground relies on binary releases (currently 2.0.1). Any idea when a new release will be made with these changes in it?

**Comment by AmitBM** [comment]
Hi tgjones, there is currently no specific date for the upcoming release. Can you build RGA from the public source code in the meantime?

**Comment by AmitBM** [comment]
Hi tgjones,

Please let us know if RGA 2.1 (released today) solved your issue.

**Comment by tgjones** [comment]
It has indeed solved the issue, thank you!

<img width="1174" alt="rga-21" src="https://user-images.githubusercontent.com/102049/55690887-2d7ef080-598f-11e9-929a-d9ced1060d0e.PNG">
