### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by Mantxurreta** [GPUOpen-Tools/RGA#32]
I cannot build it in linux.
My process:
1)I have run the .sh file because the .bat file that fails immediately.
2)Following the build instructions apparently the current folder structures does not match the instructions. I have worked that out by pointing at the folder where the files in question end up being.
3) I run make in the subfolder /RGA-master/Build/CMake/linux/Release$

Error:
1)The build fails after 40% as follows:
Last line before error:
/usr/bin/x86_64-linux-gnu-ld: /home/myuser/Downloads/GPUOpen/Common/Lib/Ext/yaml-cpp/lib/linux/gcc5/libyaml-cpp.a(exp.cpp.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
First error line:
/usr/bin/x86_64-linux-gnu-ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
RadeonGPUAnalyzerCLI/CMakeFiles/RadeonGPUAnalyzerCLI.dir/build.make:417: recipe for target '../../../../output/bin/rga-bin' failed
make[2]: *** [../../../../output/bin/rga-bin] Error 1
CMakeFiles/Makefile2:293: recipe for target 'RadeonGPUAnalyzerCLI/CMakeFiles/RadeonGPUAnalyzerCLI.dir/all' failed
make[1]: *** [RadeonGPUAnalyzerCLI/CMakeFiles/RadeonGPUAnalyzerCLI.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Thank you.

**Comment by AmitBM** [comment]
Hi Mantxurreta,

[Batch files](https://en.wikipedia.org/wiki/Batch_file) are not intended for Linux. We updated the build instructions to reflect that.

Regarding the build error, please pull the latest changes and give it another shot.

**Comment by Mantxurreta** [comment]
Hello,
With a clean build and without running the .bat file it worked.
Thank you.
