### ISSUE TITLE
Running RGA in Docker

### ISSUE THREAD

**Issue by dooglz** [GPUOpen-Tools/RGA#33]
Is there a Docker image somewhere (i.e https://github.com/RadeonOpenCompute/ROCm-docker ) that can run RGA with any of its compiler back-ends? 
I'm trying to do this myself but I'm having trouble getting the driver dependencies inside a container.

**Comment by AmitBM** [comment]
Hi dooglz,

Can you clarify what driver dependencies are missing, and also - what mode of RGA are you trying to use?
The mode which would probably be the most relevant for ROCm is the rocm-cl mode and it has no driver dependencies.

**Comment by dooglz** [comment]
To clarify, I'm not sure what the 'driver dependencies' _are_ that I need to run the various rga modes. Hence I was looking to see if there was something already out there I could peek at the docker-file for. 
All I need is opencl source->ISA. I'll investigate with Rocm-cl some more.

**Comment by dooglz** [comment]
I can confirm that `rga -s rocm-cl --isa output/isa.txt hello.cl` works under docker without needing to install any drivers or extra dependencies. My issue was I was mistakenly trying to force `-c fiji`. This method only seems to support Vega, which is fine for me, I just didn't think to omit the `-c `flag
