### ISSUE TITLE
HSLS disassamble, is fully optimized?

### ISSUE THREAD

**Issue by minerva94** [GPUOpen-Tools/RGA#38]
Apologies for the silly question, I just wanted to make sure, is the output from RGA fully optimized for HSLS? I cannot find an optimization flag to use.

I am currently using:
```

rga temp.hlsl -f PS -s hlsl --parse-isa --isa out.txt -I E:\WORK_IN_PROGRESS\C \SirEngineThe3rd\data\shaders\rasterization -p ps_5_0 -c gfx902  --il il.txt
```
Best regards

M.

**Comment by AmitBM** [comment]
Hi minerva94,

I assume that you are referring to the front-end compiler's optimization (D3D compiler). By default, rga would compile your HLSL code using the packaged d3dcompiler_*.dll, which supports several optimization-related flags, as you can see in [this page](https://docs.microsoft.com/en-us/windows/desktop/direct3dhlsl/d3dcompile-constants). 

One way to control the optimizations at the front-end stage is to pass the --DXFlags \<arg\> command line option to the tool, where \<arg\> is the decimal value of the relevant D3D compiler flags.
