### ISSUE TITLE
Issues building for Linux

### ISSUE THREAD

**Issue by godlikepanos** [GPUOpen-Tools/RGA#39]
Hi,

First some minor doc issues:

- README.md mentions Prebuild.sh but it's prebuild.sh
- README.md mentions fetch_dependencies.py but it's FetchDependencies.py

Then some build issues:

```
/xxx/more/RGA/Core/Vulkan/Backend/../../../../RGA/Utils/Vulkan/Include/rgPipelineTypes.h:10:10: fatal error: Utils/Include/rgaSharedDataTypes.h: No such file or directory
 #include <Utils/Include/rgaSharedDataTypes.h>
```

The directory casing is wrong. It's ```include``` not ```Include```

**Comment by AmitBM** [comment]
Hi godlikepanos,

Thank you for you comments - it should be fixed now.
