### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [GPUOpen-Tools/RGA#4]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [Backend::Initialize](https://github.com/GPUOpen-Tools/RGA/blob/df206ffa512b74ffb69ca3ed81ee2caca75202b3/RadeonGPUAnalyzerBackend/src/beBackend.cpp#L110 "Backend::Initialize function")
- [ISAProgramGraph::DestroyISAProgramStructure](https://github.com/GPUOpen-Tools/RGA/blob/df206ffa512b74ffb69ca3ed81ee2caca75202b3/RadeonGPUAnalyzerBackend/emulator/Parser/ISAProgramGraph.cpp#L55 "ISAProgramGraph::DestroyISAProgramStructure function")

**Comment by callan-amd** [comment]
Amit

I notice you closed most of these without commenting.  Is that because you addressed the issues – or have decided not to? Either way we should comment and not just close things.
