### ISSUE TITLE
Navi OpenCL offline(non-rocm) compilation support?

### ISSUE THREAD

**Issue by andru-kun** [GPUOpen-Tools/RGA#46]
Is there any plans to support OpenCL offline(non-rocm) compilation for Navi?

**Comment by AmitBM** [comment]
Thanks for requesting this feature. We hope to make it available in one of our upcoming releases.

**Comment by AmitBM** [comment]
Hi andru-kun,

RGA 2.3, which was released today, adds support for RDNA targets in the legacy OpenCL mode (-s cl). Please note that the latest Adrenalin driver is required for this feature.

**Comment by andru-kun** [comment]
Hi,

unfortunately doesn't work. Fails on any OpenCL file, or just hangs(using one CPU core forever at 100%, if don't specify _-I_ for _--OpenCLoption_).

I have tried my old bat-file
`%RGA% -s cl -c %ARG1% -b kernel.bin %OCL_OPTIONS% %KERNELS_PATH%%KERNEL_FILE%.cl > log.txt`
and it produce this error:
> Target GPU detected:
> 
> gfx1010 (RDNA)
> 	AMD Radeon RX 5700
> 	AMD Radeon RX 5700 XT
> 	AMD Radeon RX 5700 XT 50th Anniversary
> 
> Error: exactly one input file must be specified.

if put *.cl file at the begging, it will produce very informative:
> OpenCL Compile Error: clBuildProgram failed (CL_BUILD_PROGRAM_FAILURE).
> Error: Failed to compile opencl source (from CL to LLVM IR).

Same OpenCL options and so on works like a charm with standard OpenCL API, right now this is the only possibility to produce a kernel for RDNA...

**Comment by oscarbg** [comment]
any ETA for 2.3 Linux release to test on Linux? (seems to depend on new amdgpu-pro release)..

**Comment by AmitBM** [comment]
andru-kun -
- Have you installed the latest Adrenalin driver? What GPU do you have installed on your system?
- Can you isolate a single RGA command line invocation that fails for a specific file and share the relevant file?

oscarbg - 
Yes, as you mentioned, RGA 2.3 Linux release is pending for the relevant amdgpu-pro driver release. It might take a few weeks.

**Comment by andru-kun** [comment]
@AmitBM found a problem. Looks like "-a" for analysis output leads to that hang I described. Everything else works fine after driver re-install and reboot
