### ISSUE TITLE
Feature request: support SPIR-V input for vulkan backend.

### ISSUE THREAD

**Issue by Jasper-Bekkers** [GPUOpen-Tools/RGA#9]
As of right now it appears that RGA only takes glsl files for the vulkan backend. Ideally I'd feed it my own .spv files. It looks like `beProgramBuilderVulkan.cpp` is only missing handling for `in.spv` and `in.spvText` cmd's into `amdspv.exe` so it should be easy to add as long as `amdspv.exe` properly supports it.

**Comment by AmitBM** [comment]
Hi Jasper-Bekkers, 
We will add this feature to RGA's feature list.

**Comment by Jasper-Bekkers** [comment]
Sounds good, should be a relatively small code-change since `amdspv.exe` alread supports the hard work from what I can see (might be mistaken).

**Comment by punkUser** [comment]
Just wanted to post that we really need this or a similar tool as well! We've run into some shaders that are performing significantly worse than expected and we currently have no real visibility into what might be going on.

**Comment by danginsburg** [comment]
+1 from me too.  This would be super useful.

**Comment by AmitBM** [comment]
Hi punkUser, danginsburg,
SPIR-V as an input language will be included as a beta feature in the upcoming RGA release, which is coming soon (a matter of a few weeks).

**Comment by AmitBM** [comment]
Hi punkUser, danginsburg,
SPIR-V support was added as a beta feature to the RGA version that was released today (RGA-1.1).
We hope that you will find it useful.

**Comment by Jasper-Bekkers** [comment]
Bumping this because binary spirv seems to be crashing i the latest released version. The text spv does work though so can always pass it through spirv-dis.exe first to work around.

**Comment by AmitBM** [comment]
Hi Jasper-Bekkers, 
There is going to be an RGA release soon that will include fixes to the Vulkan backend.
If you can provide more details about the shaders and the command that you were using, we will try to make sure that the specific problem that you are seeing is resolved.

**Comment by AmitBM** [comment]
Hi Jasper-Bekkers,
Please let us know if the fixes in [RGA 1.2](https://github.com/GPUOpen-Tools/RGA/releases/tag/1.2.0.0) solved your problem.
